# -*- coding: utf-8 -*-
"""facialExpression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sTz9_rHXJ5dZs2VZQef5gQXohTQ_vKjj
"""

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/

!kaggle datasets download -d aadityasinghal/facial-expression-dataset

import zipfile
zip_ref = zipfile.ZipFile('/content/facial-expression-dataset.zip', 'r')
zip_ref.extractall('/content')
zip_ref.close()

import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense, Conv2D, MaxPooling2D, Flatten

"""generators

"""

train_ds = keras.utils.image_dataset_from_directory(
    directory = '/content/train',
    labels="inferred",
    label_mode="int",
    batch_size=32,
    image_size=(256, 256)
)

validation_ds = keras.utils.image_dataset_from_directory(
    directory = '/content/test',
    labels="inferred",
    label_mode="int",
    batch_size=32,
    image_size=(256, 256)
)

"""Normalize"""

def process(image,label):
  image = tf.cast(image/255. ,tf.float32)
  return image,label

train_ds = train_ds.map(process)
validation_ds = validation_ds.map(process)

"""CNN model training"""

model = Sequential()

model.add(Conv2D(32,kernel_size=(3,3),padding='valid',activation='relu',input_shape=(256,256,3)))
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))

model.add(Conv2D(64,kernel_size=(3,3),padding='valid',activation='relu'))
model.add(MaxPooling2D(pool_size=(2,2),strides=2,padding='valid'))



model.add(Flatten())


model.add(Dense(64,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.summary()

model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

history = model.fit(train_ds,epochs=10,validation_data=validation_ds)

import matplotlib.pyplot as plt

plt.plot(history.history['accuracy'],color='red',label='train')
plt.plot(history.history['val_accuracy'],color='blue',label='validation')
plt.legend()
plt.show()

plt.plot(history.history['loss'],color='brown',label='train')
plt.plot(history.history['val_loss'],color='green',label='validation')
plt.legend()
plt.show()

import cv2

test_img = cv2.imread('/content/rudresh.jpeg')

plt.imshow(test_img)

test_img.shape

test_img=cv2.resize(test_img,(256,256))

plt.imshow(test_img)

test_input=test_img.reshape((1,256,256,3))

model.predict(test_input)

test_img = cv2.imread('/content/sad.jpeg')

plt.imshow(test_img)

test_img.shape

test_img=cv2.resize(test_img,(256,256))

test_input=test_img.reshape((1,256,256,3))

model.predict(test_input)